### ISSUE TITLE
Add paging system to API and app list

### ISSUE THREAD

**Issue by celcodioc** [DownloadMii/DownloadMii-Website#14]
Split returned apps into 10-20 apps per page to avoid sending too much data to the user at once in long lists. This would also require the 3DS app to be updated for these changes.

**Comment by filfat** [comment]
Before we implement this, lets make sure the native app supports it.

**Comment by celcodioc** [comment]
Ok, but if we can make the website pull from a seperate "release" branch, we won't have to worry about breaking the app when doing the backend first.

**Comment by filfat** [comment]
Will do. However before we make a paging system lets make appdata work :)

  
    
    
  
  
 		 	   		  =

**Comment by celcodioc** [comment]
I'll start working on this now.

(now = when I have the time to :P)

**Comment by filfat** [comment]
I can look into it on the 3DS app once im done with 3DS_UI
