### ISSUE TITLE
AppData

### ISSUE THREAD

**Issue by filfat** [DownloadMii/DownloadMii-Website#15]
Add support for appdata by allowing the user to attach a zip file that will, in the native application get extracted in the same folder as the 3dsx file, there should be a filesize limit to 10-20mb and when the user updates the zip file the old zip should be replaced by the now one.

Appdata should use a separate blob.

**Comment by celcodioc** [comment]
Almost done - just need you to make the website not pull its files from the master branch so that I don't break the site when pushing the update for this.

**Comment by filfat** [comment]
Alright, 25mb is alright :)

**Comment by filfat** [comment]
The website now pulls from the "release" branch :)

**Comment by celcodioc** [comment]
This feature has been added in 162b009f7667b7e011b90dfd591d10287721d195.

**Comment by celcodioc** [comment]
When you've made the needed SQL changes, you can merge master into release :)

```sql
ALTER TABLE appversions
ADD appdata VARCHAR(255) NOT NULL AFTER smdh,
ADD appdata_md5 VARCHAR(32) NULL AFTER smdh_md5;

ALTER TABLE apps
MODIFY failpublishmessage VARCHAR(24) NULL;
```

I should probably use upgrade scripts later...

**Comment by filfat** [comment]
Lets implement it in the client first.
