### ISSUE TITLE
Using query string instead of hierarchical path for API app listing parameters

### ISSUE THREAD

**Issue by celcodioc** [DownloadMii/DownloadMii-Website#23]
So, the current API query for listing apps looks like `/api/Apps/.../.../`. This is pretty ineffective considering what it is dealing with.

For example, we have two different, as we call them, "second level requests" for finding applications:
```
<domain>/api/apps/Applications/[category (optional)]/[subcategory (optional)]
<domain>/api/apps/Find/[query]/[category (optional)]/[subcategory (optional)]
```
One for listing all applications, optionally filtered by category. And another for finding applications by a name/description/publisher string query, also optionally filtered by category. This makes the syntax and code messy. In addition to that, we have `TopDownloadedApps` and `TopDownloadedGames` which could just be replaced with a sorting parameter, and we could also use one instead of `ByDev`.

I think we should rewrite that part of the API to look like this:
```
<domain>/api/apps?query=blargSnes&publisher=GPL_PUBLISHER&category=Emulators&subcategory=Nintendo&sort=downloads
```
All these parameters would be optional.

However, the 3DS app needs to be updated for this, and a new "api_v2.php" file might need to be created if we want to keep the code clean (the old syntax should be kept somewhere so that old versions of DownloadMii continue working in the future).

**Comment by filfat** [comment]
I agree with this, However I'm getting less and less time each day to work on DownloadMii due to school so you might have to look into the native app too if I'm not able to do it. Otherwise go ahead :D

Sent from Windows Phone 8.1 on the Nokia Lumia 920
________________________________

**Comment by celcodioc** [comment]
Pretty much done (in the server) in b0bf0d5f5594419452ae3c13bf1b371cb748ef13, it was really quick to implement.

What will we do with the old code? I haven't tried launching the 3DS app, but if it doens't error out with the new syntax (which it shouldn't) I'm almost considering removing the old stuff and forcing users to update to the new version since the "dmii" syntax isn't changed. It's bad practice though, and a versioning system might be better :/

**Comment by filfat** [comment]
We could just keep the old version of the API and only update it if it breaks the process of updating the native app to the newest version.
Date: Sat, 24 Jan 2015 12:40:18 -0800
