### ISSUE TITLE
Individual app pages

### ISSUE THREAD

**Issue by filfat** [DownloadMii/DownloadMii-Website#25]
We should have app pages similar to Windows Store or Google Play for more information about that app (eg ability in the future for the publisher to upload Screenshots, link YouTube videos, Reviews, etc)

it should follow a url format like this "domain/apps/[guid]"

I will make a mockup soon to show what i mean.

**Comment by celcodioc** [comment]
Working on this now.

**Comment by filfat** [comment]
+1 :)

**Comment by celcodioc** [comment]
The web.config in /apps/ doesn't work.
"The page cannot be displayed because an internal server error has occurred."

I should've probably left that part to you instead of trying to make it myself :P

**Comment by celcodioc** [comment]
Well, the app viewing pages are working in 47668a153baa86906f0eafadc049a99f7e46d0b6, but not the categories (for example http://www.downloadmii.com/apps/Emulators)

**Comment by filfat** [comment]
We need to style the app page now.

**Comment by filfat** [comment]
The publisher should probably be allowed to remove screenshots(same goes for appdata) :)

**Comment by celcodioc** [comment]
Can you fix the web.config file so that category pages (i.e. http://www.downloadmii.com/apps/Games) work? Right now they show "unknown error"; it should be like how `/newapi/apps` actually is `/newapi.php`:

- If the subdirectory is `/apps/view/`, rewrite to `/apps/app.php`
- If there is a subdirectory and it isn't the above, rewrite to `/apps/index.php`

Btw, I'll take care of the appdata/screenshot removing after I'm done with the notifications.

**Comment by filfat** [comment]
Okay, i will look into it

**Comment by filfat** [comment]
Cant seem to get the rewrite to work on my local IIS server. hmm.

**Comment by filfat** [comment]
Maybe the user should be allowed to upload a optional highres(400x400px) app icon that only will be used for the website, it would make https://www.downloadmii.com/apps/ look a lot better.

**Comment by celcodioc** [comment]
I'll take care of that soon-ish :)

**Comment by filfat** [comment]
You're the best :)

**Comment by filfat** [comment]
Hey, while you are at it (If it's not too much work) could you add change log support for each release. I think the app page would look a lot nicer with it. :D

**Comment by celcodioc** [comment]
I think the change log will have to wait a little bit (so I'll start working on that after I'm done with this). I'm currently adding file deletion support too, and maybe a bit more :)

Btw, maybe we should close this so we don't go way off topic.

**Comment by filfat** [comment]
Good idea :P
