### ISSUE TITLE
/apps/ doesn't work anymore

### ISSUE THREAD

**Issue by filfat** [DownloadMii/DownloadMii-Website#30]
See https://www.downloadmii.com/apps/

**Comment by celcodioc** [comment]
Fixed (d8a71eeb879a3b599fa8f558ba533a8cc212fe75), you changed the new API file to newapi.php (IMO it should be api_v2.php or divided into version files, but whatever as long as we don't keep changing the syntax), and the apps page was stull using the old URL.
