### ISSUE TITLE
App searching doens't work on DownloadMii website

### ISSUE THREAD

**Issue by celcodioc** [DownloadMii/DownloadMii-Website#31]
`/newapi/apps?find=someapp` doesn't work on the official DownloadMii website. My guess is that the fulltext index hasn't been created for `apps.name` and `apps.description`. This SQL query would solve it:

```sql
ALTER TABLE apps
ADD FULLTEXT(name, description)
```

**Comment by filfat** [comment]
Fixed the sql problem, however i get this:
Warning: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in D:\home\site\wwwroot\common\functions.php on line 201

Fatal error: Call to a member function execute() on a non-object in D:\home\site\wwwroot\common\functions.php on line 204

**Comment by celcodioc** [comment]
Something's wrong on your end. If you execute this query you will probably get an error telling you what's wrong:

```sql
SELECT app.guid, app.name, app.publisher, app.version, app.description, app.category, app.subcategory, app.rating, app.downloads,
user.nick AS publisher, appver.number AS version, maincat.name AS category, subcat.name AS subcategory, appver.largeIcon AS largeicon, appver.3dsx_md5, appver.smdh_md5, appver.appdata_md5
FROM apps app
LEFT JOIN users user ON user.userId = app.publisher
LEFT JOIN appversions appver ON appver.versionId = app.version
LEFT JOIN categories maincat ON maincat.categoryId = app.category
LEFT JOIN categories subcat ON subcat.categoryId = app.subcategory
WHERE app.publishstate = 1
AND (MATCH(app.name) AGAINST(? WITH QUERY EXPANSION)
OR MATCH(app.description) AGAINST(? WITH QUERY EXPANSION)
OR user.nick LIKE ?)
```

**Comment by filfat** [comment]
Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '? WITH QUERY EXPANSION) OR MATCH(app.description) AGAINST(? WITH QUERY EXPANSION' at line 9

Date: Thu, 29 Jan 2015 07:59:11 -0800

**Comment by celcodioc** [comment]
I forgot to change the query, try again :P

**Comment by filfat** [comment]
It complains about full text,
even though the alter script returned just fine:
17:10:47	ALTER TABLE apps ADD FULLTEXT(name, description)	0 row(s) affected Records: 0  Duplicates: 0  Warnings: 0	2.156 sec

**Comment by celcodioc** [comment]
What's your MySQL version and the full error message?

**Comment by filfat** [comment]
Idk, the latest for Windows?response:
17:10:30	SELECT app.guid, app.name, app.publisher, app.version, app.description, app.category, app.subcategory, app.rating, app.downloads, user.nick AS publisher, appver.number AS version, maincat.name AS category, subcat.name AS subcategory, appver.largeIcon AS largeicon, appver.3dsx_md5, appver.smdh_md5, appver.appdata_md5 FROM apps app LEFT JOIN users user ON user.userId = app.publisher LEFT JOIN appversions appver ON appver.versionId = app.version LEFT JOIN categories maincat ON maincat.categoryId = app.category LEFT JOIN categories subcat ON subcat.categoryId = app.subcategory WHERE app.publishstate = 1 AND (MATCH(app.name) AGAINST('filfat' WITH QUERY EXPANSION) OR MATCH(app.description) AGAINST('filfat' WITH QUERY EXPANSION) OR user.nick LIKE '%filfat%') LIMIT 0, 1000	Error Code: 1191. Can't find FULLTEXT index matching the column list	0.172 sec

Date: Thu, 29 Jan 2015 08:14:16 -0800

**Comment by celcodioc** [comment]
Ok, I found out that `ALTER TABLE apps ADD FULLTEXT(name, description)` doesn't work. You have to do them individually:

```sql
ALTER TABLE apps
ADD FULLTEXT(name),
ADD FULLTEXT(description)
```

**Comment by filfat** [comment]
Well,
https://www.downloadmii.com/newapi/apps?find=Download

**Comment by celcodioc** [comment]
Ok, sorry about the mess (this is my first time working with fulltext indexes). You probably have multiple fulltext indexes on the name/description rows.

Delete them all with something like phpMyAdmin. Make sure you only delete the ones marked with "FULLTEXT". If you only have a console you have to list them (`SHOW INDEX FROM apps`) and then delete each one with `ALTER TABLE apps DROP INDEX indexname;`

Then do this so we won't have to mess with duplicates again:

```sql
CREATE FULLTEXT INDEX ft_name ON apps(name);
CREATE FULLTEXT INDEX ft_description ON apps(description);
```

**Comment by filfat** [comment]
Yeah... http://i.imgur.com/FsgVwB6.png ill just leave the duplicates there

**Comment by celcodioc** [comment]
You have to remove them in order for the search to work, only one fulltext per column. ;)

**Comment by filfat** [comment]
well, the original name & desc is fulltext. If I remove them we lose data...

Date: Sat, 31 Jan 2015 10:50:13 -0800

**Comment by filfat** [comment]
Here is what i mean: http://i.imgur.com/MjASw78.png

**Comment by celcodioc** [comment]
That they're called "name" and "description"? If you use the right command (`ALTER TABLE apps DROP INDEX name;`) it's safe.

Btw, scratch the indexes we just created. This is better: *facepalm*
```sql
CREATE FULLTEXT INDEX ft_name_desc ON apps(name,description);
```

**Comment by celcodioc** [comment]
Oh, and after that the API will error, but I have a commit ready that will fix it.

**Comment by filfat** [comment]
Done

Date: Sat, 31 Jan 2015 11:12:20 -0800

**Comment by celcodioc** [comment]
http://www.downloadmii.com/newapi/apps?find=downloadmii now works

Not everything works as expected, but that's more about optimization.
