### ISSUE TITLE
Notification system

### ISSUE THREAD

**Issue by filfat** [DownloadMii/DownloadMii-Website#36]
A notifications system would be a great way to tell the user if an app passed the review process etc, it would also be a great way to tell admins that there is new apps to be reviewed.

If you agree on this, the best would be to write a simple php api for the notification system so it can be used to about anything notification related. if we for example decides to in the future create a more full flexed user system where users can upload avatars, write bio etc etc get notified by email etc etc.

**Comment by celcodioc** [comment]
Ok, I'll try to take care of that within a few days.

**Comment by celcodioc** [comment]
Sorry about not telling earlier, but I haven't been able to do anything the past week (and it looks like it'll be like that for a while), so this feature is on hold on my part for now.

**Comment by celcodioc** [comment]
Status update:

The branch is fairly close to completion now. I ran into some problems with sending notifications to people with certain roles so I also created a better group system (still not full-fledged though, but can be modified to be).

What's left:
- Testing
- Adding pages for managing groups
- E-mail notifications(?)
- Prettier notification page UI(?)
- A few minor things

**Comment by filfat** [comment]
The code looks great so far! :D

**Comment by filfat** [comment]
If we decide to do E-mail notifications so should we use SendGrid thanks to their free limit of 400 emails per day :)

**Comment by celcodioc** [comment]
So, as of commit d494949126dcb6c34a882c65c8cada1d9fc4f31f it's pretty much done. Maybe we can merge tomorrow.

No email notifications yet, but I think we should add that and refine the UI later. :)

**Comment by filfat** [comment]
Just  looked into the commit, looks awesome! :D
Feel free to merge whenever you want :)

**Comment by filfat** [comment]
Hey, you mind writing a small query to update the SQL db? :)

**Comment by celcodioc** [comment]
71be8190b2d50cb602b553fd8166a4ebd6e7bd41: It's alive! :D

...well, almost. config.php hasn't been updated. Could you please update it with the three new "notification" keys (I suggest just copying them and their values from the template) and close this issue?

**Comment by filfat** [comment]
Done! :D

**Comment by celcodioc** [comment]
Great! Btw, I'll add a mod/admin page for manually sending notifications later :)

**Comment by filfat** [comment]
*like*
