### ISSUE TITLE
Appdata doesn't update when updating app

### ISSUE THREAD

**Issue by filfat** [DownloadMii/DownloadMii-Website#38]
No matter what, if you change the icon file and/or the version of the app so will the old version still show up on My Apps, Browse Apps and http://www.downloadmii.com/newapi/dmii/data

This is true for DownloadMii at least; I can not say for sure when it comes to other apps.

**Comment by filfat** [comment]
@celcodioc (offtopic, but iv sent ya a PM on gba)

**Comment by celcodioc** [comment]
Does it work now? If it does, you might be running into the filesize limit in php.ini, because it seems fixed when I test it.

**Comment by filfat** [comment]
It seems to work https://www.downloadmii.com/apps/view/9CF9C6A6-4F95-4E2A-90F2-F8DC9462B1C6
