### ISSUE TITLE
Allow mods and admins to view already published apps

### ISSUE THREAD

**Issue by filfat** [DownloadMii/DownloadMii-Website#39]
Currently the mod pages returns error 422 if you try to view a published app.
This should be possible as we might need to remove an app etc.

**Comment by celcodioc** [comment]
That doesn't happen to me on the official website. Try forcing a refresh (Ctrl+F5) on the page where you type in the app GUID (`apps.php`) and then query the app again

The mod pages still use the stupid token system so if `apps.php` is cached (which can happen for example if you use the back button to get to it) your browser will try to access `appview.php` with an old token and that will show error 422.

**Comment by filfat** [comment]
Yep, works. thanks :)
